### ISSUE TITLE
ensureDir not defined.

### ISSUE THREAD

**Issue by wilville** [5hubham5ingh/jiffy#1] opened 2024-11-27 16:15 UTC
I get this error when I run it. I assume I am missing a util. I installed node js and installed a package with the same name.

**Comment by okamigarden** [comment] 2024-11-27 18:37
I got this output too. Is yours similar to mine?

```
ReferenceError: 'ensureDir' is not defined
    at getAppMenu (applicationMenu.js:177)
    at getMenu (userMenu.js:10)
    at app (main.js:125)
    at main (main.js:27)
    at <anonymous> (main.js:7)
```

**Comment by okamigarden** [comment] 2024-11-27 19:04
I managed to fix it.

I was looking through your source code 

My steps:
```
1.  sudo pacman -S fzf
2. cd Gits/ && git clone https://github.com/5hubham5ingh/jiffy && cd jiffy
3. mkdir -p ~/.cache/jiffy && mv -t ~/.cache/jiffy applicationMenu.js fzf.js main.js userMenu.js
```

**Comment by 5hubham5ingh** [comment] 2024-11-28 17:32
The issue is fixed in the latest release.

**Closed** 2024-11-29 07:37 UTC
